### ISSUE TITLE
The `if` function is special: should be lazy.

### ISSUE THREAD

**Issue by kaj** [kaj/rsass#107]
The `if` function [is special in that it's argument should be lazily evaluated](https://sass-lang.com/documentation/modules#if).  Bootstrap 5 (and probably other common scss code) relies on this.

> I've tried running the cmd line on the new bootstrap 5 scss files but I get:
>
> ```
> Error: $weight: Expected -20 to be within 0 and 100.
>     ,
> 156 |   @return mix(white, $color, $weight);
>     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     '
>     ../../Downloads/bootstrap-5.0.0/scss/_functions.scss 156:11  import
>    ../../Downloads/bootstrap-5.0.0/scss/bootstrap-grid.scss 10:9  root stylesheet
>     ,
> 166 |   @return if($weight > 0, shade-color($color, $weight), tint-color($color, -$weight));
>     |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     '
>     ../../Downloads/bootstrap-5.0.0/scss/_functions.scss 166:57  import
>     ../../Downloads/bootstrap-5.0.0/scss/bootstrap-grid.scss 10:9  root stylesheet
>     ,
> 291 | $link-hover-color:                        shift-color($link-color, $link-shade-percentage) !default;
>     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     '
>     ../../Downloads/bootstrap-5.0.0/scss/_variables.scss 291:43  import
>     ../../Downloads/bootstrap-5.0.0/scss/bootstrap-grid.scss 11:9  root stylesheet
> ```
> 
> The JS implementation (using dart-sass) from their package.json seem to compile it without errors. Now according to their docs `mix` should be a value in between 0-100 so the error should be legit.
> It would useful to vendor a few common Sass libraries and compile them as additional tests. It also gives an idea of which missing feature is commonly used.

_Originally posted by @Keats in https://github.com/kaj/rsass/issues/3#issuecomment-835810305_

What happens in the bootstrap compiling error above is that both arguments to the `if` on line 166 is evaluated (even though only the `$if-true` one is needed) and evaluating the `$if-else` value causes an error.

**Comment by kaj** [comment]
Note: One down, n to go.  The issue with the `if` function is resolved, but rsass still cant handle bootstrap.

**Comment by Keats** [comment]
@kaj I'm running into this again on master with bootstrap 5.0.1

```
(venv) ~/C/p/rsass (master|…) [2] $ ./target/debug/rsass ~/Downloads/bootstrap-5.0.1/scss/bootstrap.scss
Error: $weight: Expected -20 to be within 0 and 100.
    ,
156 |   @return mix(white, $color, $weight);
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    '
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/_functions.scss 156:11  import
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/bootstrap.scss 10:9  root stylesheet
    ,
166 |   @return if($weight > 0, shade-color($color, $weight), tint-color($color, -$weight));
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    '
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/_functions.scss 166:57  import
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/bootstrap.scss 10:9  root stylesheet
    ,
291 | $link-hover-color:                        shift-color($link-color, $link-shade-percentage) !default;
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    '
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/_variables.scss 291:43  import
    /Users/vincentprouillet/Downloads/bootstrap-5.0.1/scss/bootstrap.scss 11:9  root stylesheet

```

**Comment by kaj** [comment]
Strange, I seem to get a different error.  Are you sure your `./target/debug/rsass` is up to date?  Note that a `cargo build` won't update it unless you have `--features=commandline` as an argument.

**Comment by Keats** [comment]
Sorry I forgot about the flag :(
