### ISSUE TITLE
@content not allowed in global context

### ISSUE THREAD

**Issue by Keats** [kaj/rsass#112]
From trying to compile bootstrap 5.0.1

Is it possible to have spanned errors or is it too complex? Right now it just prints the error message but there are many `@content` use in the whole bootstrap codebase.

**Comment by kaj** [comment]
Also, just looking at the code, I think there is a problem with the condition causing that error.  Actually, it might be most correct to just remove it.  :-)

**Comment by Keats** [comment]
Sweet thanks. Do you want me to report the bootstrap issues or is too much noise? I figure once rsass can compile bootstrap and some various sites I have lying around I can probably switch Zola from sass-sys to rsass which is pretty exciting!

**Comment by kaj** [comment]
Keep them coming!  😎   As long as they are somewhat researched and not too many at the same time, they are a valuable help in getting rsass better!

Also, having something as good as Zola use rsass would be avesome!  Though there is some use of `@extend` (see #65) in bootstrap, so I fear it will take some time getting there.
