### ISSUE TITLE
crate bogusly says `0.24.1-PRE`

### ISSUE THREAD

**Issue by jonassmedegaard** [kaj/rsass#142]
Hi,

Release `v0.25.0` was released - exciting!
However, it seems you missed bumping the version in `Cargo.toml` - t still says `0.24.1-PRE` :-/

**Comment by jonassmedegaard** [comment]
By the way (and only vaguely related to this issue): You might appreciate that I have packaged rsass for Debian - it is now sitting in the so-called [NEW queue](https://ftp-master.debian.org/new.html) awaiting a final screening before (hopefully) entering Debian officially.

**Comment by kaj** [comment]
Ah, I accidentally pushed the new release as `0.24.1-PRE` first.  Then I updated the version number, commited, pushed to crates.io ...  But forgot to push to github.  Sorry.  Now it should hopefully say v0.25.0 everywhere.

Thanks for packaging!  I hope the package docs mentions the development status, that I don't yet claim to be a complete implementation of sass.  As long as that is noted (maybe with a link to issue #3 ), I'm all for packaging.

**Comment by jonassmedegaard** [comment]
> I hope the package docs mentions the development status, that I don't yet claim to be a complete implementation of sass. As long as that is noted (maybe with a link to issue https://github.com/kaj/rsass/issues/3 ), I'm all for packaging.

The package includes your upstream README.md file, and (after your raising concern here) I added an explicit [notice in the package description](https://packages.debian.org/bookworm/rsass referencing your documentation): **NB! Not all of the official Sass specification is implemented yet. See upstream README below /usr/share/doc/rsass/ for more details.**
