### ISSUE TITLE
performance 

### ISSUE THREAD

**Issue by blackPeppper** [kaj/rsass#149]
how mush rsass faster ato compile time compare to sass command line 
at frist i am going to make a csspreprocessor in rust  because sass is slow but now ?

**Comment by kaj** [comment]
Hi!  Being written in rust, rsass has the _potential_ to be very fast.  That said, I haven't really cared about performance yet, and don't really plan to bother with that until functionality is a log more complete (see e.g. #130 and #65).  There are some cases where the current parser gets slowed down by retrying things (e.g. extremely deep levels of parenthesis).

Also, I tend to use rsass in the build stage of a web service project, not at runtime.  So for _my_ typical use case extreme performance doesn't really matter that much.  Measurments would be welcome!
