### ISSUE TITLE
Can you split the crate or move main.rs to examples? Clap is compile slow and unnecessary when use rsass in build.rs.

### ISSUE THREAD

**Issue by biluohc** [kaj/rsass#15]

**Comment by kaj** [comment]
Yes, I agree.  On the other hand, I need the command-line rsass to run the test suite.  I have looked for a way to disable the clap dependency when building rsass as a dependency, but haven't found any yet.

I think a separate -bin crate would be too inconvenient, but I'll look into a way to make the binary an optional feature of the crate.

**Comment by biluohc** [comment]
Consider move to examples and use [`[dev-dependencies]` ](http://doc.crates.io/specifying-dependencies.html) ?
```
Development dependencies

You can add a [dev-dependencies] section to your Cargo.toml whose format is equivalent to [dependencies]:

[dev-dependencies]
tempdir = "0.3"

Dev-dependencies are not used when compiling a package for building, but are used for compiling tests, examples, and benchmarks.

These dependencies are not propagated to other packages which depend on this package.

You can also have target-specific development dependencies by using dev-dependencies in the target section header instead of dependencies. For example:
```

**Comment by kaj** [comment]
Well, I'll still want to be able to `cargo install` the binary.  But I'll look into making it a feature.

**Comment by biluohc** [comment]
Ok, thanks you very much.
