### ISSUE TITLE
Do not build a no-op command line

### ISSUE THREAD

**Issue by kaj** [kaj/rsass#16]
Currently, the `commandline` feature is required to build a useful command-line interface. If the feature is not specified, [clap](https://crates.io/crates/clap) is not required and the build is much faster.

However, when the `commandline` feature is not given, a `rsass` binary is still built.  I have made it so that running this binary only fails with a message about the `commandline` feature flag.

So I would want to make the entire `main.rs` and the `[[bin]]` section of `Cargo.toml` optional, if cargo can do that?

An even nicer alternative would be to not have a feature-flag at all, but having clap as a "bin-only" dependency, and not building that when rsass itself is built as a dependency, if there is a way to make cargo do that?

**Comment by biluohc** [comment]
Try required-feature?

https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section

**Comment by kaj** [comment]
That sounds like it should work.  Thank you for the suggestion!
