### ISSUE TITLE
Parsing error when specifying quoted font name strings

### ISSUE THREAD

**Issue by kartikynwa** [kaj/rsass#175]
Using rsass version 0.28.0. If I try this code:

```rust
use rsass::compile_scss;

const SCSS_INPUT: &'static [u8] = b"
:root {
    --main-font: \"Times New Roman\", serif;
}
";

fn main() {
    compile_scss(
        SCSS_INPUT,
        rsass::output::Format {
            style: rsass::output::Style::Compressed,
            precision: 0,
        },
    )
    .unwrap();
}
```

It panics with this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse error: Tag
  ,
3 |     --main-font: "Times New Roman", serif;
  |                                   ^
  '
  - 3:35  root stylesheet', src/main.rs:17:6
```

I don't know much about CSS but this looks valid. It passes with grass and official sass CLI.

This errors with single quotes instead of double quotes as well. But if I use something like `serif, sans-serif`, the parsing succeeds.

Hope this helps.

**Comment by kaj** [comment]
Yes, this looks very much like it should be valid!  Thanks for the excellent report.  I'll convert it to a test case and see if I can find out why it happens.
