### ISSUE TITLE
1fr gets compiled to 1 fr

### ISSUE THREAD

**Issue by tw1t611** [kaj/rsass#26]
hi, just found this issue for
```css
display: grid;
grid-template-columns: 100px 1fr;
```
did output 
```css
display: grid;
grid-template-columns: 100px 1 fr;
```
which crashed the code.

**Comment by kaj** [comment]
Yes, this sounds like a bug.  It's probably easy to add `fr` to the set of known units.  Fixing so unknown units are handled correctly are probably a bit harder, but both should be done, and patches are welcome.

If noone submits a PR soonish, I'll attemt to fix it, but I guess I won't have time before christmas, and possibly not before the new year.

**Comment by tw1t611** [comment]
You are right, adding the unit just worked.
I did open a pr.
