### ISSUE TITLE
Support CSS functions with special syntax: "calc", "element", "expression", "min", "max", "progid", "url"

### ISSUE THREAD

**Issue by glebm** [kaj/rsass#42]
1. It is forbidden to declare user functions with these names.

   Dart Sass checks this in the parser:
   https://github.com/sass/dart-sass/blob/a81017275ad543fde3bced92d96b1d32c62c9014/lib/src/parse/stylesheet.dart#L716-L726

2. Expressions with these functions should be parsed as strings, not function calls.

   This is also handled in the parser in Dart Sass:
   https://github.com/sass/dart-sass/blob/a81017275ad543fde3bced92d96b1d32c62c9014/lib/src/parse/stylesheet.dart#L2250-L2311

**Comment by kaj** [comment]
Yes, this should be fixed.  The second point also means that the current parsing rules that, under some rather sketchy conditions, accepts more or less anything as a string could be limited to only affect arguments to these special functions.

**Comment by kaj** [comment]
Some of these gets fixed by #55 , but some (at least `min`, `max` and `url`) has a more complex boundary for when they should be kept verbatim and when their arguments should be evaluated.

**Comment by kaj** [comment]
I'm not sure if this is done or not.  There has been lots of small improvements to this area, in #76, #77, #78 as well as in some separate commits.
