### ISSUE TITLE
Tests: Whitespace should be normalized

### ISSUE THREAD

**Issue by glebm** [kaj/rsass#43]
Many tests fail only because the `output.css` files have some extra newlines.

This should be fixed to match sass-spec behaviour:

https://github.com/sass/sass-spec/blob/0f59164aabb3273645fda068d0fb1b879aa3f1dc/lib/sass_spec/util.rb#L5-L7

That is, normalizing the output of both `rsass` and the expectation, e.g. like this:

```rust
use std::borrow::Cow;

use regex::Regex;

// Normalizes the whitespace in the given CSS to make it easier to compare. Based on:
// https://github.com/sass/sass-spec/blob/0f59164aabb3273645fda068d0fb1b879aa3f1dc/lib/sass_spec/util.rb#L5-L7
pub fn normalize_output(css: &str) -> Cow<str> {
    lazy_static! {
        static ref RE: Regex = Regex::new("(?:\r?\n)+").unwrap();
    }
    RE.replace_all(css, "\n")
}
```

I've tried implementing this but gave up after an hour of struggling with the rust module system.

**Comment by kaj** [comment]
Ah, nice.  I was trying to get the correct number of newlines at all positions, but that wasn't really straightforward ...  And if the official spec runner normalizes the newlines, we can do the same in rsass!

I'll add it.
