### ISSUE TITLE
Expose structured information about parse errors

### ISSUE THREAD

**Issue by maxbrunsfeld** [kaj/rsass#46]
Right now, when an SCSS file fails to parse, I get back an `Error::S` that originates [here](https://github.com/kaj/rsass/blob/5036c6468dedf50e30a2c2407214c358c9db58cd/src/parser/mod.rs#L61-L64). SCSS files can be pretty large, so that 'remains' part of the message can get very long. I'd like to just report the row and column where the error occurred. Is is possible to get that information from `nom`?

**Comment by kaj** [comment]
Yes, it's certainly possible, just not implemented in rsass yet.

Improvement is needed in two ways:

1) Converting the 'remains' part to row and column numbers isn't actually that hard.  The thing that remains is a sub-slice of the byte-slice beeing parsed, so as long as the whole data is still in memory, the slice before the error can be found and the line number and column number can be calculated.
2) If parsing fails inside a block, the error often propagates outwards, and the entire block is reported as unparsed.  To fix that, some (or most) of the long `alt!(...)` and `alt_complete!(...)` parsers in `src/parser/mod.rs` needs to be converted to `switch!(...)` parsers or similar.

So, entirely doable and kind of supported by `nom`, just not done in rsass yet.

**Comment by kaj** [comment]
A first step should be to add an expected end-of-file to the end of [the sassfile parser](https://github.com/kaj/rsass/blob/5036c6468dedf50e30a2c2407214c358c9db58cd/src/parser/mod.rs#L73-L92), so we get an error at all, instead of a successfull but incomplete parse.

**Comment by kaj** [comment]
The PR #79 is a relevant improvement to this, improving the structure of `Error::ParseError` and removing the case where a parse error is handled as an `Error::S`.

The PR #62 is also relevant, taking the refactoring a bit further, but that is awaiting a release of `nom_locate`.

Then the second half still remains, currently a parse error is most often a `nom::Tag` or `nom::Alt` (in a `msg` string in `ParseError`).  We need to improve the parser to get more meaningful errors (specific errors, e.g. a parameter list needs to end with a `)`).

**Comment by kaj** [comment]
After improvements in #201 and more, I think it is finally time to consider this issue done.
