### ISSUE TITLE
Consider exclusively running specs from sass-spec.rb

### ISSUE THREAD

**Issue by nex3** [kaj/rsass#48]
It looks like many of the tests in the test/ directory are auto-generated from sass-spec. This requires this package to build in logic to understand the format of the sass-spec repo, which risks being broken by changes to sass-spec (such as https://github.com/sass/sass-spec/pull/1340). I think it's worth considering doing what Dart Sass, LibSass, and Ruby Sass do and only running the specs using the official runner.

**Comment by glebm** [comment]
I can see 2 benefits to having the tests in Rust:
1. Speed, it's *a lot* faster.
2. IIRC, the Rust team runs the cargo test suites of many packages when working on updates to the language. If the tests are not invoked via `cargo test`, this won't work.

**Comment by kaj** [comment]
A third benefit of converting the tests to rust code is that they can be executed without even building the `rsass` command-line interface, which contributes a lot to a fast test cycle during development.

I have taken a quick look at the `.hrx` files, and even though it seems very non-standard (the only code I found for unpacking it is the [ruby lib recently developed](https://github.com/google/hrx-ruby) and used in sass-spec) it also seems rather simple, so I think it won't be too hard to add `.hrx` parsing to `spectest` (the test converter).

**Comment by nex3** [comment]
The HRX specification lives at https://github.com/google/hrx.

**Comment by kaj** [comment]
I wrote a simple reader, which I hope is more or less enough for updating `spectest`.

https://crates.io/crates/hrx-get

**Comment by kaj** [comment]
As of 98f39e46b878cd75bed831ef1b9549caf101ec34, `spectest` supports reading sass-spec tests from `.hrx` files, so we can continue trying to keep up with changes there.

Thanks for the heads-up, @nex3 !

And I should mention, the number of successful tests that I update for each release is calculated by running the official sass-spec test runner.
