### ISSUE TITLE
rsass::Error does not implement std::error::Error

### ISSUE THREAD

**Issue by Boiethios** [kaj/rsass#58]
I compile my `scss` files into a function `fn compile_all() -> Result<(), Box<dyn Error>>` so that whatever the error, I can use the `?` operator. However, since the rsass `Error` does not implement the Error trait, I cannot use it that way.

Is it possible to implement this trait? I assume that it is a mere oversight.

BTW, thanks for the work, it's a great crate that allows me to not install NodeJS only for a simple static site.

**Comment by kaj** [comment]
That sounds reasonable, and yes, I think you are right in assuming this is just an oversight.  I'll fix.
