### ISSUE TITLE
@import behavior

### ISSUE THREAD

**Issue by Boiethios** [kaj/rsass#59]
The first step I do when I port a `css` to `scss` is to just change the extension, compile it, and verify that there is no regression. In my situation, the following lines:

```scss
@import "mobile.css" screen and (max-width: 60rem);
@import "desktop.css" screen and (min-width: 60rem);
```

were transformed to:

```css
@import "mobile.css" true;
@import "desktop.css" true;
```

Maybe I'm missing something, but I don't think that it's a normal behavior. The line should be copied verbatim, doesn't it?

**Comment by kaj** [comment]
Yes, that is a bug in rsass.
