### ISSUE TITLE
Support the `@use` directive

### ISSUE THREAD

**Issue by Boiethios** [kaj/rsass#60]
I define a color palette in a `_palette.scss` file:

```
$color-0: white;
```

and then I `@use` is from another file:

```
@use "palette";

$font-color: palette.$color-0;
```

I've tried as well to use an explicit namespace `@use palette as palette` or to put everything in the global namespace `@use palette as *` but I get the same error message:

```
Undefined variable: "$color-0"
```

**Comment by kaj** [comment]
Yes, `@use` / modules is a relatively new addition to sass, and is still not supported by any implementation other than dart sass.   You don't get an error message for the `@use` line itself, as it could be a general @-rule that should be preserved to the css.

**Comment by kaj** [comment]
@Boiethios , I think your code should work with release 0.16.

**Comment by kaj** [comment]
I'll close this issue now.  `@use` is mainly supported, and there are separate issues for the pieces remaining.
