### ISSUE TITLE
Rsass hangs on many parens

### ISSUE THREAD

**Issue by connorskees** [kaj/rsass#68]
`rsass` begins to run very slowly for this input,
```
a {
  color: (((((((((((((((((((;
}
```
this runs forever,
```
a {
    color: ((((((((((((((((((((((((((((((((((((((((((((a))))))))))))))))))))))))))))))))))))))))))));
}
```

This is preventing a default run of the sass-spec and occurs on the most recent commit on master.

**Comment by kaj** [comment]
Ah, yes, it seems to become quadratic with reparsing each subparenthensis both as a potential dictionary and then as a value.  It should be possible to either rewrite that so it just parses the expression (which might be a key) once, and then checks for a colon, or to limit the "key" to not start with a parenthesis.

https://github.com/kaj/rsass/blob/9aafa67871127f0b24ae0327dd467440449fa904/src/parser/value.rs#L171-L187
