### ISSUE TITLE
Split Value into css::Value and sass::Value

### ISSUE THREAD

**Issue by jnicklas** [kaj/rsass#9]
I've been trying to get a grip on how to separate printing of the final CSS from the compilation of Sass to CSS, I think I have a pretty good idea on how we can get there, if you think that this is a goal worth working toward.

My thinking is to try to get rid of the `scope` being passed around in output_style, and to apply the entire Sass compilation before we get to printing. As a first step to this, it makes sense to work from the bottom up, the bottom seems to be `Value`. Eventually I'd like to split SassItem into `sass::Item` and `css::Item` in a similar manner.

Basically the idea is to have two separate enums like this:

``` rust
mod css {
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub enum CssValue {
        Call(String, Vec<(Option<String>, CssValue)>),
        Div(Box<CssValue>, Box<CssValue>, bool, bool),
        Literal(String, Quotes),
        List(Vec<CssValue>, ListSeparator),
        Numeric(Rational, Unit, bool, bool),
        Color(Rational, Rational, Rational, Rational, Option<String>),
        BinOp(Box<Value>, Operator, Box<Value>),
        Null,
        True,
        False,
    }
}

mod sass {
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub enum Value {
        Call(String, CallArgs),
        Div(Box<Value>, Box<Value>, bool, bool),
        Literal(String, Quotes),
        List(Vec<Value>, ListSeparator),
        Numeric(Rational, Unit, bool, bool),
        Paren(Box<Value>),
        Variable(String),
        Color(Rational, Rational, Rational, Rational, Option<String>),
        Null,
        True,
        False,
        BinOp(Box<Value>, Operator, Box<Value>),
        UnaryOp(Operator, Box<Value>),
        Interpolation(Box<Value>),
    }
}
```

As you can see, these enums are very similar. The changes are: function calls have been applied, parens stripped, calculations performed, unary operators applied, interpolations resolved, and so on.

Most importantly, a `css::Value` is fully resolved without having to have a `scope`. This is the exact operation that `Value::evaluate(scope)` already performs, so the signature of `evaluate` would change to:

``` rust
impl Value {
  pub fn evaluate(&self, scope: &Scope) -> CssValue
}
```

Basically this is something we already do, but we'd be using separate types for an unevaluated and for an evaluated Value, I think this makes sense from an architecture perspective as well, since it clarifies (or forces us to clarify) whether a value is evaluated or not (for example when it is a function argument or return value).

**Comment by jnicklas** [comment]
@kaj what do you think? Is this a sensible idea?

**Comment by kaj** [comment]
I have considered it, but decided against it at the time.  Might still be a good idea, though.

What made med decide against is two things:

Sometimes, I think a value actually should be evaluated more than once, e.g. both when declaring a variable and when using it (though I'm not really sure about that).

Also, declaring almost all values feels like a lot of duplicate code, which I don't like.  (yes, I know there is a log of near-duplicate code in output_style).  But maybe it's not that much that needs to be duplicated.  Only `sass::Value` needs parsing and only `css::Value` needs formatting ...

**Comment by kaj** [comment]
Also note that there is a small start of this done in `output_style.rs`, in the form of `enum CssBodyItem`.  It is used for some buffering and to implement namespace rules.

**Comment by jnicklas** [comment]
> Also, declaring almost all values feels like a lot of duplicate code

I think we can reduce some of the duplication by moving towards having structs inside the enums, for example, like this:

``` rust
mod value {
  struct Color(Rational, Rational, Rational, Rational, Option<String>)
}

mod css {
    pub enum Value {
        Color(value::Color),
        // ...
    }
}

mod sass {
    pub enum Value {
        Color(value::Color),
        // ...
    }
}
```

I think we'd want to do this at a later point though, since it will take a lot of work to get there.

This has the added benefit of making it a little easier to factor some of the large match statements into smaller chunks, though I'm not sure whether that's desirable, since it will spread out the code much more.

There will always be some added duplication with this proposed design though, that's a tradeoff compared to the current implementation.

**Comment by kaj** [comment]
An other way would be to skip the enum altogether and have `sass::Value` and `css::Value` as traits instead.  The different kinds of values could be implemented as separate structs that implement one or both of the traits.

I haven't really considered the trade-offs between a trait with multiple structs vs. an enum, I just started with the enum because it seemed simpler and isn't available in other languages I have used ...

**Comment by jnicklas** [comment]
I think the `enum` approach has some advantages, most importantly the ability to pattern match on the enum's variants, which I think is very useful. Also the ability to actually see which variants exist can be pretty useful. A trait based approach might also mean that we'd need to resort to dynamic dispatch in some cases, which isn't a huge cost, but still it'd be nice to avoid IMO.

Personally I'd prefer the current approach with enums over using a trait.

**Comment by kaj** [comment]
Yes, I like pattern matching over enums too, but it does tend to make some functions rather large.  Using a method call with separate implementations makes for shorter functions, but instead spread out over a larger part of the code.  But yes, that would mean dynamic dispatch.

On the other hand, I don't know that the efficiency of dynamic dispatch would be worse than the multiple comparisions or jumptables that a large switch is compiled to ...

**Comment by jnicklas** [comment]
I've been playing around with this, and it turns out to be quite challenging to split Value into two, since there are a lot of places where one or the other is used, and it's not obvious which one they should accept.

Nevertheless, I think it's worth it to do this split. I think the increased type safety due to this will be worth it, since there are already some places in the code base, where there are lurking issues due to this. For example, when a Value is evaluated, and a Variable is encountered, the value of the variable is fetched from the Scope. The Scope always contains evaluated variables, but this is not enforced by the type system. Additionally, after the value is fetched from the scope, it is actually evaluated [again](https://github.com/kaj/rsass/blob/master/src/value/mod.rs#L141).

This is not a problem in practice, since the value is always evaluated anyway, and another evaluate will simply be a no-op, but IMO it's still a potentially tricky source for bugs. If we ever put an unevaluated value into a scope somehow, it would mean that the value will be evaluated at the usage site, instead of being evaluated at the definition site, which will lead to silently incorrect output.

The same kind of problem occurs with functions, which could currently theoretically return a variable, which seems a bit strange.

**Comment by kaj** [comment]
With functions, there is also the problem that they would need to be able to take both a `sass::Value` and a `css::Value` for any parameter value.  So maybe `sass::Value` needs to impl `From<css::Value>`?  Then the parameter type for functions could be `&Into<sass::Value>` ?

Maybe a way to do that and avoid some code duplicating would be that one variant in the `sass::Value` enum could be `Css(css::Value)` ?  But then again, some stuff would need to be more or less duplicated anyway, since at least a `sass::Value::List` would need to be different from a `css::Value::List`, since they would need different item types.

**Comment by jnicklas** [comment]
I've already been working on this a bit and in my implementation I went with functions both receiving and returning only `css::Value`. IMO this kind of makes sense, since the function arguments should be evaluated already when they are passed to the function, the function shouldn't be responsible for evaluating them. The same goes for the return value. Returning for example a `variable` is pretty strange, imo. I admit that semantically it feels a bit odd that a Sass functions receives and returns CSS values and not Sass values.

**Comment by kaj** [comment]
This is essentially done now that PR #13 is merged.  Is there anything else we need to consider before closing this issue, @jnicklas ?
