### ISSUE TITLE
Support `&[thing=""]` syntax

### ISSUE THREAD

**Issue by mfeckie** [kaj/rsass#91]
Do you have a sense of how difficult it would be to support this type of syntax ?

```scss
&[class$='link'] {`
```

I'm happy to put some work into it myself if you can point me in the right direction.

**Comment by kaj** [comment]
Yes, that should be supported.  It might be as simple as adding `"$="` to the matched Attribute operators in the parser:

https://github.com/kaj/rsass/blob/b85519315dd3e1c7dc98e38773be07e127149ccc/src/parser/selectors.rs#L63

And I guess the same should go for `~=` and `^=`.

**Comment by kaj** [comment]
Fixed in #92, Thanks!
