### ISSUE TITLE
Panick in planifolia sqrt

### ISSUE THREAD

**Issue by alvra** [kaj/rsass#98]
When using the math functions from planifolia, I'm getting a panic computing a sqrt.

```
thread 'main' panicked at 'attempt to multiply with overflow',
.cargo/registry/src/github.com-1ecc6299db9ec823/num-integer-0.1.44/src/lib.rs:795:1
```

Example:
```rust
use rsass::compile_scss;

fn main() {
    let sass = b"@import \"node_modules/sass-planifolia/sass/math.scss\";\
               \n$x: sqrt(2);\
               \na { size: $x }";
    let css = compile_scss(sass, Default::default()).unwrap();
    println!("{}", String::from_utf8_lossy(&css));
}
```

https://github.com/xi/sass-planifolia/blob/master/sass/math.scss

**Comment by kaj** [comment]
Looking at the error, I guess this is a case I've kind of known about for a while but not gotten around to fix: numbers in rsass can be isize rational, bignum rational or f64, but there is not enough conversions in place to handle case like this.  If I try `sqrt(2.0000000000000000000000000001)` instead, i get bignum rationals and the code works (but rather slow, taking 14.32s on my machine).

So, this should be fixed.  In the mean time, if you need a sqrt function, sass impllements [the sass:math sqrt function](https://sass-lang.com/documentation/modules/math#sqrt).  The following sass code gives the expected output (in 0.00s):

```scss
@use "sass:math" as *;
$x: sqrt(2);
a { size: $x }
```

**Comment by alvra** [comment]
Thanks for your suggestion. Using the builtin `sqrt` or a literal with up to 10 digits seems to work ok.
For future reference, there is a simpler way to reproduce this without importing planifolia:

```scss
$x: 1.4142135623;
a { size: $x * $x }
```
